import fs from "node:fs/promises";
import path from "node:path";

import ora from "ora";
import inquirer from "inquirer";

import { resolveStateDir, loadState, saveState } from "../state.mjs";
import { StatuteApiClient } from "../api/client.mjs";
import { applyTemplateOperations } from "../fix/codemod.mjs";
import { createBackupSession, backupFile } from "../fix/rollback.mjs";
import { scanRepo } from "../scan/index.mjs";
import { matchFindingsToGapIds } from "../match.mjs";
import { isGitRepo, ensureBranch, getGitStatusPorcelain } from "../util/git.mjs";
import { ensureDir, writeJsonAtomic, walkFiles } from "../util/fs.mjs";
import { writePatchFile } from "../fix/patch.mjs";

function pickTargetFilesByGlob(repoRoot, globs) {
  // Minimal glob support for v1: only **/*.{ext,ext2} patterns.
  const exts = new Set();
  for (const g of globs) {
    const m = g.match(/\*\*\/\*\.\{(.+)\}$/);
    if (m) m[1].split(",").forEach((e) => exts.add(e.trim().replace(/^\./, "")));
  }
  return { exts: Array.from(exts) };
}

async function ensureLangChainHitlSupport({ repoRoot, template }) {
  const hitlOps = (template?.operations ?? []).filter((op) => op?.op === "langchain_hitl_guardrail");
  if (hitlOps.length === 0) return;

  // v1: only supports the default relative import.
  const importFrom = hitlOps[0]?.import_from ?? "./statute/hitl";
  if (importFrom !== "./statute/hitl") return;

  const dir = path.join(repoRoot, "statute");
  const filePath = path.join(dir, "hitl.ts");

  try {
    await fs.stat(filePath);
    return; // exists
  } catch {
    // continue
  }

  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(
    filePath,
    [
      `// Statute OS — Human-in-the-loop guardrail (LangChain)`,
      `// Auto-generated by \`statute fix\`. Customize to route approvals to your preferred workflow.`,
      ``,
      `import { createInterface } from "node:readline/promises";`,
      `import { stdin as input, stdout as output } from "node:process";`,
      ``,
      `async function promptApprove(message: string): Promise<boolean> {`,
      `  if (process.env.STATUTE_HITL_AUTO_APPROVE === "true") return true;`,
      `  if (!input.isTTY) {`,
      `    throw new Error("STATUTE_HITL_REQUIRES_TTY: set STATUTE_HITL_AUTO_APPROVE=true for non-interactive runs");`,
      `  }`,
      `  const rl = createInterface({ input, output });`,
      `  try {`,
      `    const answer = await rl.question(\`\${message} [y/N] \`);`,
      `    return String(answer).trim().toLowerCase().startsWith("y");`,
      `  } finally {`,
      `    rl.close();`,
      `  }`,
      `}`,
      ``,
      `// LangChain passes callback handlers as plain objects at runtime; subclassing is optional.`,
      `export class StatuteHITLCallbackHandler {`,
      `  name = "statute_hitl";`,
      ``,
      `  async handleToolStart(tool: any, input: any) {`,
      `    const ok = await promptApprove(\`Approve tool call: \${tool?.name ?? "tool"}\`);`,
      `    if (!ok) throw new Error("STATUTE_HITL_DENIED_TOOL_CALL");`,
      `  }`,
      ``,
      `  async handleLLMStart(_llm: any, prompts: any) {`,
      `    const preview = Array.isArray(prompts) ? String(prompts[0] ?? "").slice(0, 120) : "";`,
      `    const ok = await promptApprove(\`Approve LLM call (preview): \${preview}\`);`,
      `    if (!ok) throw new Error("STATUTE_HITL_DENIED_LLM_CALL");`,
      `  }`,
      `}`,
      ``,
    ].join("\n"),
    "utf8",
  );
}

export async function runFix(opts) {
  const cwd = process.cwd();
  const stateDir = resolveStateDir(opts.config, cwd);
  const spinner = ora("Preparing fix...").start();

  try {
    const state = await loadState(stateDir);
    if (opts.assessmentId) {
      state.context = { ...(state.context ?? {}), assessment_id: opts.assessmentId };
      await saveState(stateDir, state);
    }
    const lastScan = state.last_scan ?? null;
    if (!lastScan) throw new Error("NO_SCAN_FOUND: run `statute scan` first");

    const gaps = lastScan.gaps ?? [];
    const selectedGapId =
      opts.gapId ??
      (
        await inquirer.prompt([
          {
            type: "list",
            name: "gap_id",
            message: "Select a gap to remediate",
            choices: gaps.map((g) => ({ name: `${g.gap_id} (${g.control_id})`, value: g.gap_id })),
          },
        ])
      ).gap_id;

    const gap = gaps.find((g) => g.gap_id === selectedGapId);
    if (!gap) throw new Error("GAP_NOT_FOUND_IN_LAST_SCAN");
    if (!gap.remediation_template_id) throw new Error("NO_TEMPLATE_FOR_GAP");
    if (!state.api_url && !opts.apiUrl) throw new Error("STATUTE_API_URL_REQUIRED_FOR_FIX");

    const api = new StatuteApiClient({
      apiUrl: opts.apiUrl ?? state.api_url,
      token: opts.token,
      debug: opts.debug,
      stateDir,
    });
    await api.assertHasScanCredits();
    spinner.text = `Fetching template ${gap.remediation_template_id}...`;
    const template = await api.getTemplate(gap.remediation_template_id);

    if (!opts.dryRun) {
      spinner.text = "Ensuring remediation support files...";
      await ensureLangChainHitlSupport({ repoRoot: cwd, template });
    }

    // Git integration
    const git = await isGitRepo(cwd);
    if (git && opts.branch !== false) {
      const dirty = await getGitStatusPorcelain(cwd);
      if (dirty.trim().length) {
        spinner.stop();
        const { proceed } = await inquirer.prompt([
          { type: "confirm", name: "proceed", message: "Git working tree is dirty. Continue?", default: false },
        ]);
        if (!proceed) return;
        spinner.start();
      }
      const branchName = `statute/fix-${gap.gap_id}`;
      spinner.text = `Creating branch ${branchName}...`;
      await ensureBranch(cwd, branchName);
    }

    spinner.text = "Selecting target files...";
    const { exts } = pickTargetFilesByGlob(cwd, template.target.globs);
    const allFiles = (await walkFiles(cwd)).filter((f) => {
      const ext = path.extname(f).slice(1);
      return exts.length === 0 || exts.includes(ext);
    });

    let backupRoot = null;
    const startBackup = async () => {
      if (backupRoot) return backupRoot;
      backupRoot = await createBackupSession({ stateDir });
      return backupRoot;
    };

    spinner.text = "Applying remediation (AST)...";
    /** @type {string[]} */
    const changed = [];
    /** @type {Array<{beforePath: string, afterPath: string}>} */
    const patchPairs = [];
    const tmpDir = path.join(stateDir, "tmp");
    await ensureDir(tmpDir);

    for (const file of allFiles) {
      const before = await fs.readFile(file, "utf8");
      const after = applyTemplateOperations({ source: before, operations: template.operations });
      if (after !== before) {
        changed.push(file);
        if (!opts.dryRun) {
          const root = await startBackup();
          await backupFile({ backupRoot: root, repoRoot: cwd, file });
          await fs.writeFile(file, after, "utf8");
        } else {
          const rel = path.relative(cwd, file);
          const beforePath = path.join(tmpDir, "before", rel);
          const afterPath = path.join(tmpDir, "after", rel);
          await ensureDir(path.dirname(beforePath));
          await ensureDir(path.dirname(afterPath));
          await fs.writeFile(beforePath, before, "utf8");
          await fs.writeFile(afterPath, after, "utf8");
          patchPairs.push({ beforePath, afterPath });
        }
      }
    }

    if (opts.dryRun) {
      spinner.text = "Generating patch...";
      const patchOut =
        opts.patchOut ??
        path.join(stateDir, "patches", `${gap.gap_id}.patch`);
      await writePatchFile({ repoRoot: cwd, pairs: patchPairs, outPath: patchOut });
      spinner.succeed(`Dry-run patch written: ${patchOut}`);
      return;
    }

    spinner.text = "Post-fix audit...";
    const rescan = await scanRepo({ repoRoot: cwd, stateDir });
    const gapsAfter = matchFindingsToGapIds(rescan.findings, state.manifest);

    const stillFailing = gapsAfter.some((g) => g.gap_id === gap.gap_id);
    spinner.stop();

    const report = {
      gap_id: gap.gap_id,
      changed_files: changed.map((f) => path.relative(cwd, f)),
      post_fix_gap_present: stillFailing,
      scanned_at: new Date().toISOString(),
    };
    await writeJsonAtomic(path.join(stateDir, "last-fix.json"), report);

    state.last_scan = { ...rescan, gaps: gapsAfter, context: state.context };
    await saveState(stateDir, state);

    if (!opts.json) {
      console.log(`Fixed ${gap.gap_id}. Changed files: ${changed.length}`);
      console.log(`Post-fix audit: ${stillFailing ? "FAILED" : "PASSED"}`);
    } else {
      console.log(JSON.stringify(report, null, 2));
    }

    if (stillFailing) process.exitCode = 2;
  } catch (err) {
    spinner.fail("Fix failed.");
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.startsWith("NO_CREDITS:")) {
      console.error("No credits available to run this remediation. Purchase credits or contact your Statute OS admin.");
    } else if (opts.debug) {
      console.error(err);
    } else {
      // Keep the default output compact but actionable.
      console.error(msg);
    }
    process.exitCode = 1;
  }
}
